version: "3.8"

services:
  web1:
    container_name: php
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/app
    networks:
      - symfony_app

  database:
    container_name: db
    platform: linux/x86_64
    image: mysql:8
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - symfony_app
    volumes:
      - ./docker/database:/var/lib/mysql

  cache:
    image: redis:7.2.4
    ports:
      - "6340:6379"
    networks:
      - symfony_app

networks:
  symfony_app:
    driver: bridge

volumes:
  database: