version: "3"

services:
  web1:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/app
    networks:
      - symfony_app

  db:
    platform: linux/x86_64
    image: mysql:8
    networks:
      - symfony_app
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

  cache:
    image: redis:7.2.4
    ports:
      - "6340:6379"
    networks:
      - symfony_app

networks:
  symfony_app:
    driver: bridge

